plugins {
    id 'java'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation project(':api')

    compileOnly 'org.jetbrains:annotations:24.0.0'

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}
