plugins {
    id 'java'
}

repositories {
    mavenCentral()

    maven {
        url 'https://jitpack.io'
    }
}

dependencies {
    implementation project(':api')
    
    implementation 'com.google.code.gson:gson:2.8.8'
    implementation 'com.google.inject:guice:7.0.0'
    implementation 'com.github.Carleslc.Simple-YAML:Simple-Yaml:1.8.4'
    
    compileOnly 'org.jetbrains:annotations:24.0.0'
    compileOnly 'org.projectlombok:lombok:1.18.34'
    
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}
