plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

repositories {
    mavenCentral()

    maven {
        url 'https://jitpack.io'
    }
}

dependencies {
    implementation project(':api')
    implementation 'com.google.inject:guice:7.0.0'
    implementation 'com.google.code.gson:gson:2.8.9'
    implementation 'com.github.Carleslc.Simple-YAML:Simple-Yaml:1.8.4'

    compileOnly 'org.projectlombok:lombok:1.18.34'
    compileOnly 'org.jetbrains:annotations:24.1.0'

    annotationProcessor 'org.projectlombok:lombok:1.18.34'
    
    testCompileOnly 'org.jetbrains:annotations:24.1.0'
    testCompileOnly 'org.projectlombok:lombok:1.18.34'

    testImplementation platform('org.junit:junit-bom:5.11.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'

    testAnnotationProcessor 'org.projectlombok:lombok:1.18.34'

    testImplementation 'org.mockito:mockito-core:5.13.0'
    testImplementation 'org.mockito:mockito-junit-jupiter:5.13.0'
}

test {
    useJUnitPlatform()
}

shadowJar {
    archiveFileName = String.format('%s-%s-%s.jar', project(':').name, project.name, project(':').version)
}

processResources {
    filesMatching('plugin.yml') {
        filter {
            it.replace('%version%', project(':').version)
        }
    }
}
