plugins {
    id 'java'
    id 'maven-publish'
}

repositories {
    mavenCentral()
}

dependencies {
    compileOnly 'org.jetbrains:annotations:26.0.2'
    compileOnly 'org.projectlombok:lombok:1.18.38'

    annotationProcessor 'org.projectlombok:lombok:1.18.38'
}

publishing {
    repositories {
        maven {
            url 'https://repository.eternalempires.dev/private'
            credentials {
                username System.getenv('IGXSYS_REED_USER')
                password System.getenv('IGXSYS_REED_TOKEN')
            }
        }
    }

    publications {
        mavenJava(MavenPublication) {
            from components.java
            artifactId String.format('%s-%s', project(':').name, project.name)
            groupId project(':').group
            version project(':').version
        }
    }
}