name: Create release

on:
  pull_request:
    types:
      - closed
    branches:
      - main
      - develop

permissions:
  contents: write

jobs:
  create-release:
    uses: EternalEmpires/java-ci/.github/workflows/create-release.yml@main
    secrets:
      IGXSYS_REED_TOKEN: ${{ secrets.IGXSYS_REED_TOKEN }}
      IGXSYS_REED_USER: ${{ secrets.IGXSYS_REED_USER }}